### PR TITLE
sorted imports to fix pep8 warning

### PR DESCRIPTION
**Pull request by smitthakkar96**

### CODE REVIEW

**Comment by nigelbabu** [comment]
Does this work? I'm reasonably confident it won't.

**Comment by smitthakkar96** [comment]
Yes it will I tested it

**Comment by nigelbabu** [comment]
Doesn't work for me.

**Comment by nigelbabu** [comment]
```
(fstat) nigelb:fstat/ (smitthakkar96-pep8) $ ./manage.py runserver                                                                                                                                      [18:44:42]
Traceback (most recent call last):
  File "./manage.py", line 4, in <module>
    from fstat import app, db
  File "/home/nigelb/code/fstat/fstat/__init__.py", line 6, in <module>
    from controller import index
  File "/home/nigelb/code/fstat/fstat/controller.py", line 3, in <module>
    from fstat import app, db
ImportError: cannot import name app
```

**Pull request closed without merging**
